apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: secretMountPath
      value: "/var/run/secrets/kubernetes.io/serviceaccount" # Default mount path
